import { mkdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const rootDir = path.resolve(__dirname, '..');

const outputPath = path.join(rootDir, 'styles.css');

const sourceFiles = [
	'src/styles/settings.css',
	'src/styles/shared.css',
	'src/features/slash-command/styles.css',
	'src/features/blocks/styles.css',
	'src/features/image/styles.css',
	'src/features/text-styling/styles.css',
	'src/features/symbol-picker/styles.css',
];

const header = `/* -------------------------------------------------------------------------
 * Better Edit — plugin UI styles
 * Generated from feature-local source files. Do not edit this file directly.
 * These styles apply only to ephemeral widget DOM, never to file content.
 * File content always uses inline styles only.
 * -------------------------------------------------------------------------*/`;

async function buildStyles() {
	const chunks = [header];

	for (const relativePath of sourceFiles) {
		const absolutePath = path.join(rootDir, relativePath);
		const css = await readFile(absolutePath, 'utf8');
		chunks.push(css.trimEnd());
	}

	await mkdir(path.dirname(outputPath), { recursive: true });
	await writeFile(outputPath, `${chunks.join('\n\n')}\n`, 'utf8');
}

await buildStyles();
