import emojilib from 'emojilib';

export interface SymbolEntry {
	char: string;
	name: string;
	keywords: string[];
}

export const MATH_SYMBOLS: SymbolEntry[] = [
	// Arithmetic & Relations
	{ char: '±', name: 'plus minus', keywords: ['pm', 'plus', 'minus'] },
	{ char: '×', name: 'times multiply', keywords: ['multiply', 'cross', 'cdot'] },
	{ char: '÷', name: 'divide', keywords: ['division', 'obelus'] },
	{ char: '≠', name: 'not equal', keywords: ['neq', 'unequal', 'ne'] },
	{ char: '≈', name: 'approximately equal', keywords: ['approx', 'similar', 'tilde'] },
	{ char: '≡', name: 'identical congruent', keywords: ['equiv', 'congruent', 'identical'] },
	{ char: '≤', name: 'less than or equal', keywords: ['leq', 'le', 'less equal'] },
	{ char: '≥', name: 'greater than or equal', keywords: ['geq', 'ge', 'greater equal'] },
	{ char: '≪', name: 'much less than', keywords: ['ll', 'much less'] },
	{ char: '≫', name: 'much greater than', keywords: ['gg', 'much greater'] },
	{ char: '∝', name: 'proportional to', keywords: ['prop', 'propto'] },
	{ char: '∞', name: 'infinity', keywords: ['inf', 'infty'] },
	{ char: '°', name: 'degree', keywords: ['deg', 'angle'] },
	{ char: '′', name: 'prime', keywords: ['prime', 'minute', 'derivative'] },
	{ char: '″', name: 'double prime', keywords: ['double prime', 'second'] },
	{ char: '‰', name: 'per mille', keywords: ['permille', 'promille'] },
	// Logic
	{ char: '∧', name: 'logical and', keywords: ['and', 'wedge', 'conjunction'] },
	{ char: '∨', name: 'logical or', keywords: ['or', 'vee', 'disjunction'] },
	{ char: '¬', name: 'logical not', keywords: ['neg', 'not', 'negation'] },
	{ char: '∀', name: 'for all universal', keywords: ['forall', 'universal', 'all'] },
	{ char: '∃', name: 'there exists', keywords: ['exists', 'existential', 'some'] },
	{ char: '∄', name: 'there does not exist', keywords: ['nexists', 'not exists'] },
	{ char: '⊤', name: 'top true', keywords: ['true', 'tautology', 'top'] },
	{ char: '⊥', name: 'bottom false perpendicular', keywords: ['false', 'contradiction', 'perp', 'bottom'] },
	// Sets
	{ char: '∅', name: 'empty set', keywords: ['emptyset', 'empty', 'nothing', 'null'] },
	{ char: '∈', name: 'element of', keywords: ['in', 'belongs', 'member'] },
	{ char: '∉', name: 'not element of', keywords: ['notin', 'not member'] },
	{ char: '⊂', name: 'subset of', keywords: ['subset', 'sub'] },
	{ char: '⊃', name: 'superset of', keywords: ['superset', 'sup'] },
	{ char: '⊆', name: 'subset or equal', keywords: ['subseteq', 'subset equal'] },
	{ char: '⊇', name: 'superset or equal', keywords: ['supseteq', 'superset equal'] },
	{ char: '∪', name: 'union', keywords: ['cup', 'union'] },
	{ char: '∩', name: 'intersection', keywords: ['cap', 'intersect'] },
	{ char: 'ℕ', name: 'natural numbers', keywords: ['natural', 'naturals', 'nat'] },
	{ char: 'ℤ', name: 'integers', keywords: ['integers', 'int', 'zahlen'] },
	{ char: 'ℚ', name: 'rational numbers', keywords: ['rational', 'rationals'] },
	{ char: 'ℝ', name: 'real numbers', keywords: ['real', 'reals'] },
	{ char: 'ℂ', name: 'complex numbers', keywords: ['complex'] },
	// Calculus & Analysis
	{ char: '∑', name: 'sum summation', keywords: ['sum', 'sigma', 'summation'] },
	{ char: '∏', name: 'product', keywords: ['product', 'prod', 'pi'] },
	{ char: '∫', name: 'integral', keywords: ['int', 'integral'] },
	{ char: '∬', name: 'double integral', keywords: ['iint', 'double integral'] },
	{ char: '∭', name: 'triple integral', keywords: ['iiint', 'triple integral'] },
	{ char: '∂', name: 'partial derivative', keywords: ['partial', 'del'] },
	{ char: '∇', name: 'nabla gradient del', keywords: ['nabla', 'gradient', 'del', 'laplacian'] },
	{ char: '√', name: 'square root', keywords: ['sqrt', 'root', 'radical'] },
	{ char: '∛', name: 'cube root', keywords: ['cbrt', 'cube root'] },
	// Arrows
	{ char: '←', name: 'left arrow', keywords: ['left', 'arrow', 'larr', 'gets'] },
	{ char: '→', name: 'right arrow', keywords: ['right', 'arrow', 'rarr', 'to'] },
	{ char: '↑', name: 'up arrow', keywords: ['up', 'arrow', 'uarr'] },
	{ char: '↓', name: 'down arrow', keywords: ['down', 'arrow', 'darr'] },
	{ char: '↔', name: 'left right arrow', keywords: ['leftrightarrow', 'horizontal', 'harr', 'bidir'] },
	{ char: '↕', name: 'up down arrow', keywords: ['updownarrow', 'vertical'] },
	{ char: '↗', name: 'north east arrow', keywords: ['northeast', 'diagonal up right'] },
	{ char: '↘', name: 'south east arrow', keywords: ['southeast', 'diagonal down right'] },
	{ char: '↙', name: 'south west arrow', keywords: ['southwest', 'diagonal down left'] },
	{ char: '↖', name: 'north west arrow', keywords: ['northwest', 'diagonal up left'] },
	{ char: '⇐', name: 'left double arrow', keywords: ['Leftarrow', 'implies left'] },
	{ char: '⇒', name: 'right double arrow implies', keywords: ['Rightarrow', 'implies', 'therefore'] },
	{ char: '⇑', name: 'up double arrow', keywords: ['Uparrow', 'double up'] },
	{ char: '⇓', name: 'down double arrow', keywords: ['Downarrow', 'double down'] },
	{ char: '⇔', name: 'left right double arrow iff', keywords: ['Leftrightarrow', 'iff', 'biconditional'] },
	{ char: '↦', name: 'maps to', keywords: ['mapsto', 'function map'] },
	{ char: '↺', name: 'counterclockwise arrow', keywords: ['ccw', 'rotate left', 'loop'] },
	{ char: '↻', name: 'clockwise arrow', keywords: ['cw', 'rotate right', 'loop'] },
	// Greek uppercase
	{ char: 'Α', name: 'Alpha uppercase', keywords: ['alpha', 'greek'] },
	{ char: 'Β', name: 'Beta uppercase', keywords: ['beta', 'greek'] },
	{ char: 'Γ', name: 'Gamma uppercase', keywords: ['gamma', 'greek'] },
	{ char: 'Δ', name: 'Delta uppercase', keywords: ['delta', 'greek', 'change', 'difference'] },
	{ char: 'Ε', name: 'Epsilon uppercase', keywords: ['epsilon', 'greek'] },
	{ char: 'Ζ', name: 'Zeta uppercase', keywords: ['zeta', 'greek'] },
	{ char: 'Η', name: 'Eta uppercase', keywords: ['eta', 'greek'] },
	{ char: 'Θ', name: 'Theta uppercase', keywords: ['theta', 'greek', 'angle'] },
	{ char: 'Ι', name: 'Iota uppercase', keywords: ['iota', 'greek'] },
	{ char: 'Κ', name: 'Kappa uppercase', keywords: ['kappa', 'greek'] },
	{ char: 'Λ', name: 'Lambda uppercase', keywords: ['lambda', 'greek'] },
	{ char: 'Μ', name: 'Mu uppercase', keywords: ['mu', 'greek'] },
	{ char: 'Ν', name: 'Nu uppercase', keywords: ['nu', 'greek'] },
	{ char: 'Ξ', name: 'Xi uppercase', keywords: ['xi', 'greek'] },
	{ char: 'Π', name: 'Pi uppercase', keywords: ['pi', 'greek'] },
	{ char: 'Ρ', name: 'Rho uppercase', keywords: ['rho', 'greek'] },
	{ char: 'Σ', name: 'Sigma uppercase', keywords: ['sigma', 'greek', 'sum'] },
	{ char: 'Τ', name: 'Tau uppercase', keywords: ['tau', 'greek'] },
	{ char: 'Υ', name: 'Upsilon uppercase', keywords: ['upsilon', 'greek'] },
	{ char: 'Φ', name: 'Phi uppercase', keywords: ['phi', 'greek'] },
	{ char: 'Χ', name: 'Chi uppercase', keywords: ['chi', 'greek'] },
	{ char: 'Ψ', name: 'Psi uppercase', keywords: ['psi', 'greek'] },
	{ char: 'Ω', name: 'Omega uppercase', keywords: ['omega', 'greek'] },
	// Greek lowercase
	{ char: 'α', name: 'alpha', keywords: ['alpha', 'greek'] },
	{ char: 'β', name: 'beta', keywords: ['beta', 'greek'] },
	{ char: 'γ', name: 'gamma', keywords: ['gamma', 'greek'] },
	{ char: 'δ', name: 'delta', keywords: ['delta', 'greek', 'change'] },
	{ char: 'ε', name: 'epsilon', keywords: ['epsilon', 'greek', 'small'] },
	{ char: 'ζ', name: 'zeta', keywords: ['zeta', 'greek'] },
	{ char: 'η', name: 'eta', keywords: ['eta', 'greek'] },
	{ char: 'θ', name: 'theta', keywords: ['theta', 'greek', 'angle'] },
	{ char: 'ι', name: 'iota', keywords: ['iota', 'greek'] },
	{ char: 'κ', name: 'kappa', keywords: ['kappa', 'greek'] },
	{ char: 'λ', name: 'lambda', keywords: ['lambda', 'greek'] },
	{ char: 'μ', name: 'mu micro', keywords: ['mu', 'greek', 'micro'] },
	{ char: 'ν', name: 'nu', keywords: ['nu', 'greek'] },
	{ char: 'ξ', name: 'xi', keywords: ['xi', 'greek'] },
	{ char: 'π', name: 'pi', keywords: ['pi', 'greek', '3.14'] },
	{ char: 'ρ', name: 'rho', keywords: ['rho', 'greek', 'density'] },
	{ char: 'σ', name: 'sigma', keywords: ['sigma', 'greek', 'std dev'] },
	{ char: 'τ', name: 'tau', keywords: ['tau', 'greek', '6.28'] },
	{ char: 'υ', name: 'upsilon', keywords: ['upsilon', 'greek'] },
	{ char: 'φ', name: 'phi', keywords: ['phi', 'greek', 'golden ratio'] },
	{ char: 'χ', name: 'chi', keywords: ['chi', 'greek'] },
	{ char: 'ψ', name: 'psi', keywords: ['psi', 'greek'] },
	{ char: 'ω', name: 'omega', keywords: ['omega', 'greek', 'angular'] },
];

export const EMOJI_SYMBOLS: SymbolEntry[] = Object.entries(emojilib).map(([char, keywords]) => ({
	char,
	name: (keywords[0] ?? char).replace(/_/g, ' '),
	keywords: keywords.map(k => k.replace(/_/g, ' ')),
}));
